{{- range $key, $val := .Values.apis }}
  {{- if and $val.enabled $val.scaling }}
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ (printf "%s-%s-hpa" (include "chart.name" $) $key) | kebabcase }}
  labels:
    app.kubernetes.io/name: {{ $key | kebabcase }}
    app.kubernetes.io/component: api
    app.kubernetes.io/instance: {{ $.Release.Name }}
    app.kubernetes.io/managed-by: {{ $.Release.Service }}
    app.kubernetes.io/part-of: {{ include "chart.name" $ }}
    helm.sh/chart: {{ $.Chart.Name }}
    {{- with $val.scaling.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with $val.scaling.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}

spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ printf "%s-%s" (include "chart.name" $) $key | kebabcase }}
  minReplicas: {{ default 1 $val.scaling.minReplicas }}
  maxReplicas: {{ default 10 $val.scaling.maxReplicas }}
  metrics:
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: {{ default 70 $val.scaling.metrics.memory }}
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ default 70 $val.scaling.metrics.cpu }}
  {{- end }}
{{- end }}
