{{- range $api := .Values.apis }}
  {{- if $api.enabled }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ printf "%s-%s" (include "chart.name" $) $api.name }}
  namespace: {{ $.Values.global.namespace | default $.Release.Namespace }}
  labels:
    app.kubernetes.io/name:        {{ $api.name }}
    app.kubernetes.io/component:   api
    app.kubernetes.io/instance:    {{ $.Release.Name }}
    app.kubernetes.io/managed-by:  {{ $.Release.Service }}
    app.kubernetes.io/part-of:     {{ include "chart.name" $ }}
    helm.sh/chart:                 {{ $.Chart.Name }}
    {{- with $api.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with $api.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  replicas: {{ $api.replicas | default 1 }}
  {{- with $api.strategy }}
  strategy:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  selector:
    matchLabels:
      app.kubernetes.io/name:      {{ $api.name }}
      app.kubernetes.io/component: api
      app.kubernetes.io/instance:  {{ $.Release.Name }}

  template:
    metadata:
      labels:
        app.kubernetes.io/name:        {{ $api.name }}
        app.kubernetes.io/component:   api
        app.kubernetes.io/instance:    {{ $.Release.Name }}
        app.kubernetes.io/managed-by:  {{ $.Release.Service }}
        app.kubernetes.io/part-of:     {{ include "chart.name" $ }}
        helm.sh/chart:                 {{ $.Chart.Name }}
        {{- with $api.labels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- with $api.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}

    spec:
      serviceAccountName: {{ $api.serviceAccount.name | default "default" }}
      {{- with $api.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}

      containers:
        - name: {{ $api.name }}
          {{- $image := get $api "image" | default dict }}
          image: "{{ get $image "registry" | default $.Values.global.image.registry }}/{{ get $image "repository" | default $.Values.global.image.repository }}:{{ get $image "tag" | default $.Values.global.image.tag | default $.Chart.AppVersion }}"
          imagePullPolicy: {{ $api.imagePullPolicy | default "IfNotPresent" }}

          ports:
            - name: http
              containerPort: {{ $api.port | default 8000 }}
              protocol: TCP
            {{- with $api.additionalPorts }}
            {{- toYaml . | nindent 12 }}
            {{- end }}

          {{- with $api.command }}
          command:
            {{- toYaml . | nindent 12 }}
          {{- end }}

          {{- with $api.args }}
          args:
            {{- toYaml . | nindent 12 }}
          {{- end }}

          {{- if or $.Values.global.env $api.env }}
          env:
            {{- with $.Values.global.env }}
            {{- range $key, $val := . }}
            - name:  {{ $key }}
              value: {{ $val | quote }}
            {{- end }}
            {{- end }}
            {{- with $api.env }}
            {{- range . }}
            - name:  {{ .name }}
              value: {{ .value | quote }}
            {{- end }}
            {{- end }}
          {{- end }}

          {{- if or $api.envFrom (not (empty $.Values.global.env)) }}
          envFrom:
            - secretRef:
                name: {{ include "activeloop-neohorizon.fullname" $ }}-secrets
            {{- with $api.envFrom }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          {{- end }}

          {{- with $api.probes }}
            {{- if .enabled }}
              {{- with .readinessProbe }}
          readinessProbe:
              {{- toYaml . | nindent 12 }}
              {{- end }}

              {{- with .livenessProbe }}
          livenessProbe:
              {{- toYaml . | nindent 12 }}
              {{- end }}

              {{- with .startupProbe }}
          startupProbe:
              {{- toYaml . | nindent 12 }}
              {{- end }}
            {{- end }}
          {{- end }}   # closes “with $api.probes”

          {{- with $api.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}

          {{- with $api.securityContext | default $.Values.global.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}

      {{- with $api.nodeSelector | default $.Values.global.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}

      {{- with $api.affinity | default $.Values.global.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}

      {{- with $api.tolerations | default $.Values.global.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}

      {{- with $api.podSecurityContext | default $.Values.global.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
  {{- end }}
{{- end }}
