{{- range $api := .Values.apis }}
  {{- if $api.ingress.enabled }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ printf "%s-%s-ingress" (include "chart.name" $) $api.name }}
  namespace: {{ $.Values.global.namespace | default $.Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ $api.name }}
    app.kubernetes.io/component: api
    app.kubernetes.io/instance: {{ $.Release.Name }}
    app.kubernetes.io/managed-by: {{ $.Release.Service }}
    app.kubernetes.io/part-of: {{ include "chart.name" $ }}
    helm.sh/chart: {{ $.Chart.Name }}
    {{- with $api.ingress.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with $api.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}

spec:
  {{- with $api.ingress.className }}
  ingressClassName: {{ . | quote }}
  {{- end }}

  rules:
  {{- range $host := $api.ingress.hosts }}
    - host: {{ $host.host }}
      http:
        paths:
          {{- range $path := $host.paths }}
          - path: {{ $path.path }}
            pathType: {{ $path.pathType | default "Prefix" }}
            backend:
              service:
                name: {{ printf "%s-%s-svc" (include "chart.name" $) $api.name }}
                port:
                  number: {{ $api.service.port | default 80 }}
          {{- end }}
  {{- end }}

  {{- with $api.ingress.tls }}
  tls:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- end }}
{{- end }}
