apiVersion: v1
kind: Secret
metadata:
  name: {{ include "activeloop-neohorizon.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/part-of: {{ include "chart.name" . }}
    helm.sh/chart: {{ .Chart.Name }}
type: Opaque
stringData:
  USE_DEEPLAKE: "true"
  USE_RABBITMQ: "true"
  RABBITMQ_URL: {{ include "activeloop-neohorizon.rabbitmqConnection" . | trim | quote }}
  POSTGRES_DB: {{ default .Values.postgresql.auth.database .Values.global.config.postgres_db | trim | quote }}
  POSTGRES_HOST: {{ include "activeloop-neohorizon.postgresqlHost" . | trim | quote }}
  POSTGRES_PASSWORD: {{ default .Values.postgresql.auth.password .Values.global.config.postgres_password | trim | quote }}
  POSTGRES_PORT: {{ default .Values.postgresql.primary.service.ports.postgresql .Values.global.config.postgres_port | quote | trim }}
  POSTGRES_USER: {{ default .Values.postgresql.auth.username .Values.global.config.postgres_user | trim | quote }}
  AL_API_KEY: {{ required "api key is required" .Values.global.config.api_key | trim | quote }}
  VISUAL_MODEL_URL: {{ default ( printf "%s-%s-svc.%s.svc.cluster.local" (include "chart.name" $) "visual_model" .Release.Namespace ) .Values.global.config.visual_model_url | trim | kebabcase | quote }}
  EMBEDDING_MODEL_URL: {{ default ( printf "%s-%s-svc.%s.svc.cluster.local" (include "chart.name" $) "embedding_model" .Release.Namespace ) .Values.global.config.embedding_model_url | trim | kebabcase | quote }}
