{{- range $api := .Values.apis }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ printf "%s-%s-svc" (include "chart.name" $) $api.name }}
  namespace: {{ $.Values.global.namespace | default $.Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ $api.name }}
    app.kubernetes.io/component: api
    app.kubernetes.io/instance: {{ $.Release.Name }}
    app.kubernetes.io/managed-by: {{ $.Release.Service }}
    app.kubernetes.io/part-of: {{ include "chart.name" $ }}
    helm.sh/chart: {{ $.Chart.Name }}
    {{- with $api.service.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with $api.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}

spec:
  type: {{ default "ClusterIP" $api.service.type }}

  {{- with $api.service.clusterIP }}
  clusterIP: {{ . }}
  {{- end }}

  {{- with $api.service.externalIPs }}
  externalIPs:
    {{- toYaml . | nindent 4 }}
  {{- end }}

  {{- with $api.service.loadBalancerIP }}
  loadBalancerIP: {{ . }}
  {{- end }}

  {{- with $api.service.loadBalancerSourceRanges }}
  loadBalancerSourceRanges:
    {{- toYaml . | nindent 4 }}
  {{- end }}

  {{- if and (eq $api.service.type "LoadBalancer") $api.service.loadBalancerClass }}
  loadBalancerClass: {{ $api.service.loadBalancerClass | quote }}
  {{- end }}

  ports:
    - name: http
      port: {{ $api.service.port | default 80 }}
      targetPort: {{ $api.port | default 8000 }}
      protocol: TCP
    {{- if $api.service.nodePort }}
      nodePort: {{ $api.service.nodePort }}
    {{- end }}
    {{- with $api.service.additionalPorts }}
    {{- toYaml . | nindent 4 }}
    {{- end }}

  selector:
    app.kubernetes.io/name: {{ $api.name }}
    app.kubernetes.io/component: api
    app.kubernetes.io/instance: {{ $.Release.Name }}
    {{- with $api.service.selectorLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}

  {{- with $api.service.sessionAffinity }}
  sessionAffinity: {{ . }}
  {{- end }}
{{- end }}
