apiVersion: v1
kind: Secret
metadata:
  name: {{ include "activeloop-neohorizon.fullname" . }}-secrets
  namespace: {{ $.Values.global.namespace | default $.Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ $.Chart.Name }}
    app.kubernetes.io/managed-by: {{ $.Release.Service }}
    app.kubernetes.io/part-of: {{ include "chart.name" $ }}
    helm.sh/chart: {{ $.Chart.Name }}
type: Opaque
stringData:
  RABBITMQ_URL: {{ include "activeloop-neohorizon.rabbitmqConnection" . | trim | quote }}
  POSTGRES_DB: {{ $.Values.postgresql.auth.database | trim | quote }}
  POSTGRES_HOST: {{ include "activeloop-neohorizon.postgresqlHost" . | trim | quote }}
  POSTGRES_PASSWORD: {{ $.Values.postgresql.auth.password | trim | quote }}
  POSTGRES_PORT: {{ $.Values.postgresql.primary.service.ports.postgresql | quote | trim }}
  POSTGRES_USER: {{ $.Values.postgresql.auth.username | trim | quote }}
  {{- range $key, $val := .Values.global.env }}
  {{ $key }}: {{ $val | quote }}
  {{- end }}
