{{- range $worker := .Values.workers }}
  {{- if $worker.enabled }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ printf "%s-%s" (include "chart.name" $) $worker.name }}
  namespace: {{ $.Values.global.namespace | default $.Release.Namespace }}
  labels:
    app.kubernetes.io/name:        {{ $worker.name }}
    app.kubernetes.io/component:   worker
    app.kubernetes.io/instance:    {{ $.Release.Name }}
    app.kubernetes.io/managed-by:  {{ $.Release.Service }}
    app.kubernetes.io/part-of:     {{ include "chart.name" $ }}
    helm.sh/chart:                 {{ $.Chart.Name }}
    {{- with $worker.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with $worker.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  replicas: {{ $worker.replicas | default 1 }}
  {{- with $worker.strategy }}
  strategy:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  selector:
    matchLabels:
      app.kubernetes.io/name:      {{ $worker.name }}
      app.kubernetes.io/component: worker
      app.kubernetes.io/instance:  {{ $.Release.Name }}

  template:
    metadata:
      labels:
        app.kubernetes.io/name:        {{ $worker.name }}
        app.kubernetes.io/component:   worker
        app.kubernetes.io/instance:    {{ $.Release.Name }}
        app.kubernetes.io/managed-by:  {{ $.Release.Service }}
        app.kubernetes.io/part-of:     {{ include "chart.name" $ }}
        helm.sh/chart:                 {{ $.Chart.Name }}
        {{- with $worker.labels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- with $worker.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}

    spec:
      serviceAccountName: {{ $worker.serviceAccount.name | default "default" }}
      {{- with $worker.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}

      containers:
        - name: {{ $worker.name }}
          {{- $image := get $worker "image" | default dict }}
          image: "{{ get $image "registry" | default $.Values.global.image.registry }}/{{ get $image "repository" | default $.Values.global.image.repository }}:{{ get $image "tag" | default $.Values.global.image.tag | default $.Chart.AppVersion }}"
          imagePullPolicy: {{ $worker.imagePullPolicy | default "IfNotPresent" }}

          {{- with $worker.command }}
          command:
            {{- toYaml . | nindent 12 }}
          {{- end }}

          {{- with $worker.args }}
          args:
            {{- toYaml . | nindent 12 }}
          {{- end }}

          {{- if or $.Values.global.env $worker.env }}
          env:
            {{- with $.Values.global.env }}
            {{- range $key, $val := . }}
            - name:  {{ $key }}
              value: {{ $val | quote }}
            {{- end }}
            {{- end }}
            {{- with $worker.env }}
            {{- range . }}
            - name:  {{ .name }}
              value: {{ .value | quote }}
            {{- end }}
            {{- end }}
          {{- end }}

          {{- if or $worker.envFrom (not (empty $.Values.global.env)) }}
          envFrom:
            - secretRef:
                name: {{ include "activeloop-neohorizon.fullname" $ }}-secrets
            {{- with $worker.envFrom }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          {{- end }}

          {{- with $worker.probes }}
            {{- if .enabled }}
              {{- with .readinessProbe }}
          readinessProbe:
              {{- toYaml . | nindent 12 }}
              {{- end }}

              {{- with .livenessProbe }}
          livenessProbe:
              {{- toYaml . | nindent 12 }}
              {{- end }}

              {{- with .startupProbe }}
          startupProbe:
              {{- toYaml . | nindent 12 }}
              {{- end }}
            {{- end }}
          {{- end }}

          {{- with $worker.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}

          {{- with $worker.securityContext | default $.Values.global.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}

      {{- with $worker.nodeSelector | default $.Values.global.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}

      {{- with $worker.affinity | default $.Values.global.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}

      {{- with $worker.tolerations | default $.Values.global.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}

      {{- with $worker.podSecurityContext | default $.Values.global.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
  {{- end }}
{{- end }}
