{{- range $key, $val := .Values.workers }}
  {{- if $val.serviceAccount }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ $val.serviceAccount.name | default (printf "%s-%s" (include "chart.name" $) $key) | kebabcase }}
  namespace: {{ include "final.namespace" $ }}
  labels:
    app.kubernetes.io/name: {{ $key }}
    app.kubernetes.io/component: worker
    app.kubernetes.io/instance: {{ $.Release.Name }}
    app.kubernetes.io/managed-by: {{ $.Release.Service }}
    app.kubernetes.io/part-of: {{ include "chart.name" $ }}
    helm.sh/chart: {{ $.Chart.Name }}
    {{- with $val.serviceAccount.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with $val.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- end }}
{{- end }}
